# Generated by Django 2.2.28 on 2022-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
