# Generated by Django 2.2.28 on 2022-06-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletic.Athletic')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Modality')),
            ],
        ),
    ]
