# Generated by Django 2.2.28 on 2022-06-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='genre',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], default='Misto', max_length=10),
        ),
    ]
