# Generated by Django 2.2.28 on 2022-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_athletic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_board',
            field=models.BooleanField(default=False, verbose_name='Diretoria'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Membro'),
        ),
    ]
