# Generated by Django 2.2.28 on 2022-06-07 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20220607_0044'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_time', models.DateTimeField()),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Modality')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_team_1', to='team.Team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_team_2', to='team.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.Tournament')),
            ],
        ),
    ]
